# This is a basic workflow to help you get started with Actions

name: Test Steps

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: my first step
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: James
          MIDDLE_NAME: Kirk
          LAST_NAME: Spock
        run: |
          echo $MY_VAR
          echo $FIRST_NAME
          echo $MIDDLE_NAME
          echo $LAST_NAME
      - name: second step
        if: success()
        run: echo "The previous job has run successfully"
      - name: third step
        if: failure()
        run: echo "Failure on second step"
      - name: my third step
        uses: actions/checkout@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
